all: main

CC = clang
override CFLAGS += -g -Wno-everything -pthread -lm

SRCS = $(shell find . -name '.ccls-cache' -type d -prune -o -type f -name '*.c' -print)
HEADERS = $(shell find . -name '.ccls-cache' -type d -prune -o -type f -name '*.h' -print)

LIB_SRCS_STATIC = fred_john.c
LIB_SRCS_SHARED = bill_sam.c

LIB_OBJS_STATIC = $(LIB_SRCS_STATIC:.c=.o)
LIB_OBJS_SHARED = $(LIB_SRCS_SHARED:.c=.o)

STATIC_LIB = libstatic.a
SHARED_LIB = libshared.so

FPIC = -fPIC
$(STATIC_LIB): $(LIB_OBJS_STATIC)
	ar crv $@ $(LIB_OBJS_STATIC)

$(SHARED_LIB): $(LIB_OBJS_SHARED)
	$(CC) -shared -o $@ $(LIB_OBJS_SHARED) $(FPIC)
	
main: $(SRCS) $(HEADERS)
	$(CC) $(CFLAGS) $(SRCS) -o "$@"

main-debug: $(SRCS) $(HEADERS)
	$(CC) $(CFLAGS) -O0 $(SRCS) -o "$@"

clean:
	rm -f main main-debug